(define (main world undocumented)
  (cons 0 step))

(define (step state world)
  (let* ((wmap (world-map world))
         (lman (lm-status world))
         (loc (lm-location lman))
         (up (get-up loc))
         (down (get-down loc))
         (left (get-left loc))
         (right (get-right loc))
         (dir (cond ((useful? wmap up) +up+)
                    ((useful? wmap down) +down+)
                    ((useful? wmap left) +left+)
                    ((useful? wmap right) +right+)
                    ((non-blocked? wmap up) +up+)
                    ((non-blocked? wmap right) +right+)
                    ((non-blocked? wmap down) +down+)
                    ((non-blocked? wmap left) +left+)
                    (#t 42))))
    (cons 0 dir)))
